// packages/ext-web-components-boilerplate-angular-cli/src/app/home/home.component.ts
declare var Ext: any;
import { Component, HostBinding } from '@angular/core';
import data from './data';

@Component({
    selector: 'home-app',
    styles: [``],
    templateUrl: 'home.component.html'
  })
  export default class HomeComponent {
    @HostBinding('style.height') public height: string = '100%';
    gridCmp:any;
    store:any;

    readyGrid = (event) => {
      this.gridCmp = event.detail.cmp;
      this.store = Ext.create('Ext.data.Store', {
          fields: ['name', 'email', 'phone', 'hoursTaken', 'hoursRemaining'],
          data,
      });

      this.gridCmp.setStore(this.store);
    }

    onSearch = (event) => {
        this.gridCmp.getStore().clearFilter();
        const newValue = event.detail.newValue;

        if (newValue.length) {
            const newValueStr = newValue.toLowerCase();

            this.gridCmp.getStore().filterBy((record) => {
                const { name, email, phone } = record.data;
                return name.toLowerCase().indexOf(newValueStr) > -1
            || email.toLowerCase().indexOf(newValueStr) > -1
            || phone.toLowerCase().indexOf(newValueStr) > -1;
            });
        }
    }
  }
  <ext-grid
    (ready)="readyGrid($event)"
    height="100%"
    width="100%"
  >
    <ext-toolbar docked="top">
      <ext-searchfield
          ui="faded"
          placeholder="Search..."
          (change)="onSearch($event)"
          responsiveConfig='{
            "width <= 576": { "flex": "1" },
            "width > 576": { "flex": "undefined" }
          }'
      >
      </ext-searchfield>
    </ext-toolbar>
    <ext-column
      text="Name"
      flex="2"
      dataIndex="name"
      resizable="true"
    >
    </ext-column>
    <ext-column
      text="Email"
      flex="3"
      dataIndex="email"
      resizable="true"
      responsiveConfig='{
        "width <= 576": { "hidden": true },
        "width > 576": { "hidden": false }
      }'
    >
    </ext-column>
    <ext-column
      text="Phone"
      flex="2"
      dataIndex="phone"
      resizable="true"
    >
    </ext-column>
  </ext-grid>

// packages/ext-web-components-boilerplate-vue/src/components/Home.vue
<template>
  <ext-grid
    v-on:ready="readyGrid($event)"
    height="100%"
  >
    <ext-toolbar docked="top">
      <ext-searchfield
        ui="faded"
        placeholder="Search..."
        v-on:change="onSearch($event)"
        responsiveConfig='{
          "width <= 576": { "flex": "1" },
          "width > 576": { "flex": "undefined" }
        }'
      />
    </ext-toolbar>
    <ext-column
      text="Name"
      flex="2"
      dataIndex="name"
      resizable="true"
    >
    </ext-column>
    <ext-column
      text="Email"
      flex="3"
      dataIndex="email"
      resizable="true"
      responsiveConfig='{
        "width <= 576": { "hidden": true },
        "width > 576": { "hidden": false }
      }'
    >
    </ext-column>
    <ext-column
      text="Phone"
      flex="2"
      dataIndex="phone"
      resizable="true"
    >
    </ext-column>
  </ext-grid>
</template>

<script>
  import HomeData from './HomeData.js';
  export default {
      name: 'Home',
      methods: {
        readyGrid: function(event) {
            this.gridCmp = event.detail.cmp;
            const store = Ext.create('Ext.data.Store', {
              fields: ['name', 'email', 'phone', 'hoursTaken', 'hoursRemaining'],
              data: HomeData,
            });

            this.gridCmp.setStore(store);
        },

        onSearch: function(event) {
            this.gridCmp.getStore().clearFilter();
            const newValue = event.detail.newValue;

            if (newValue.length) {
                const newValueStr = newValue.toLowerCase();
                this.gridCmp.getStore().filterBy((record) => {
                    const { name, email, phone } = record.data;
                    return name.toLowerCase().indexOf(newValueStr) > -1
                    || email.toLowerCase().indexOf(newValueStr) > -1
                    || phone.toLowerCase().indexOf(newValueStr) > -1;
                });
            }
        }
    }
  }
</script>
