// packages/ext-web-components-vue-boilerplate/src/components/About.vue
<template>
  <ext-panel
    height="100%"
    shadow="true"
    bodyPadding="20px"
  >
    <h1>About this App</h1>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Etiam eget leo sed mi imperdiet dictum a id turpis.
        Suspendisse a ante eu lorem lacinia vestibulum.
        Suspendisse volutpat malesuada ante, sed fermentum massa auctor in.
        Praesent semper sodales feugiat.
        Class aptent taciti sociosqu ad litora torquent per conubia nostra,
        per inceptos himenaeos.
        Mauris mauris ante, suscipit id metus non, venenatis tempor tortor.
        In ornare tempor ipsum.
        Sed rhoncus augue urna, ut dapibus odio fringilla vitae.
        Phasellus malesuada mauris ut nulla varius sodales.
        Sed et leo luctus, venenatis felis sit amet, vehicula nibh.
        Curabitur fringill a fringilla nibh, porttitor lacinia urna vestibulum eu.
        Integer ac aliquet risus. Curabitur imperdiet quis purus at consectetur.
        Sed ornare vitae felis a scelerisque.
        Donec mi purus, auctor sit amet molestie nec, imperdiet auctor mauris.
    </p>
  </ext-panel>
</template>

<script>
  export default {
      name: 'About'
  }
</script>

// packages/ext-web-components-boilerplate-react/src/about/About.jsx
import React from 'react';

export default class About extends React.Component {
    render() {
        return (
            <ext-panel
                height="100%"
                bodyPadding="20px"
            >
                <h1>About this App</h1>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Etiam eget leo sed mi imperdiet dictum a id turpis.
                    Suspendisse a ante eu lorem lacinia vestibulum.
                    Suspendisse volutpat malesuada ante, sed fermentum massa auctor in.
                    Praesent semper sodales feugiat.
                    Class aptent taciti sociosqu ad litora torquent per conubia nostra,
                    per inceptos himenaeos.
                    Mauris mauris ante, suscipit id metus non, venenatis tempor tortor.
                    In ornare tempor ipsum.
                    Sed rhoncus augue urna, ut dapibus odio fringilla vitae.
                    Phasellus malesuada mauris ut nulla varius sodales.
                    Sed et leo luctus, venenatis felis sit amet, vehicula nibh.
                    Curabitur fringill a fringilla nibh, porttitor lacinia urna vestibulum eu.
                    Integer ac aliquet risus. Curabitur imperdiet quis purus at consectetur.
                    Sed ornare vitae felis a scelerisque.
                    Donec mi purus, auctor sit amet molestie nec, imperdiet auctor mauris.
                </p>
            </ext-panel>
        );
    }
}
