// packages/ext-web-components-boilerplate-vue-cli/src/App.vue
<template>
  <ext-container viewport="true">
    <ext-titlebar height="52px" docked="top" weight="10">
      <ext-button iconCls="x-fa fa-bars" v-on:tap="toggleTree($event)" v-on:ready="readyToggleButton($event)" ></ext-button>
      <span href="#" class="app-title">Sencha ExtWebComponentsModern Vue 7.1 Boilerplate</span>
    </ext-titlebar>
    <div style="width:100vw; height: calc(100vh - 52px); display: flex;">
      <div :style="panelStyle">
        <ext-panel
          docked="left"
          border="true"
          shadow="true"
          scrollable="y"
          resizable='{"edges": "east", "dynamic": "true"}'
          header="false"
          :collapsed="collapsed"
          collapsible='{"direction": "left"}'
          height="100%"
          v-on:ready="readyNavTreePanel($event)"
        >
          <ext-treelist
            ui="nav"
            expanderFirst="false"
            expanderOnly="false"
            v-on:ready="readyNavTreelist($event)"
            v-on:itemclick="navTreelistSelectionChange($event)"
          >
          </ext-treelist>
        </ext-panel>
      </div>
      <div style="width: 100vw;">
        <router-view></router-view>
      </div>
    </div>
  </ext-container>
</template>

<script>
  import getMenu from './menu.js';
  const menu = getMenu();

  export default {
      name: 'app',
      data() {
          return {
              treeStore: Ext.create('Ext.data.TreeStore', {
                  rootVisible: true,
                  root: {
                      hash: 'all',
                      iconCls: 'x-fa fa-home',
                      leaf: false,
                      text: 'All',
                      children: menu
                  }
                }),
              isInitial: true,
              wait: 2,
              collapsed: false,
              panelStyle: "width: 200px;"
          }
      },
      methods: {
          readyNavTreePanel: function(event) {
              this.navTreePanelCmp = event.detail.cmp;
              document.body.style.margin = 0;

              if(Ext.os.is.Phone) {
                  if (this.collapsed) {
                      this.collapsed = false;
                  } else {
                      this.collapsed = true;
                  }
              }
          },
          readyNavTreelist: function(event) {
              this.navTreelistCmp = event.detail.cmp;
              this.navTreelistCmp.setStore(this.treeStore);
              const node = this.treeStore.findNode('hash', 'home');
              this.navTreelistCmp.setSelection(node);
          },
          readyToggleButton: function(event) {
              this.navButton = event.detail.cmp;

              if (Ext.os.is.Phone) {
                  this.navButton.setHidden(false);
                  this.panelStyle = "";
              } else {
                  this.navButton.setHidden(true);
              }
          },
          navTreelistSelectionChange: function(event) {
              const record = event.detail.info.node.data.text.toLowerCase();
              this.navigate(record);
          },
          navigate: function(record) {
              if (record == null) {
                  console.log('it was null');
                  return;
              }

              this.$router.push( `/${record}`);

              if(Ext.os.is.Phone) {
                  if (this.collapsed) {
                      this.collapsed = false;
                  } else {
                      this.collapsed = true;
                  }
              }
          },
          toggleTree: function(event) {
              if (this.collapsed) {
                  this.collapsed = false;
              } else {
                  this.collapsed = true;
              }
          }
      }
  }
</script>

// packages/ext-web-components-boilerplate-angular-cli/src/app/app.component.ts
declare var Ext: any;
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-root',
  styles: [``],
  templateUrl: './app.component.html'
})
export class AppComponent {
  treeStore: any;
  navTreeRoot: any;
  navTreelistCmp: any;
  search:any;
  collapsed:boolean;
  navTreePanelCmp:any;
  filterRegex:any;

  constructor(public router: Router) {
    this.navTreeRoot = {
      iconCls: 'x-fa fa-home',
      text: 'All',
      hash: 'all',
      leaf: false,
      children: [
        { text: 'Home',  hash: '/home', iconCls: 'x-fa fa-home', leaf: true, default:true},
        { text: 'About', hash: '/about', iconCls: 'x-fa fa-question',leaf:true }
      ]
    };
    this.treeStore = Ext.create('Ext.data.TreeStore', {
        rootVisible: true,
        root: this.navTreeRoot
    });
    this.collapsed = false;

    if (Ext.os.is.Phone) {
        this.collapsed = true;
    }
  }
  
readyNavTreePanel = (event) => {
    this.navTreePanelCmp = event.detail.cmp;

    this.navTreePanelCmp.setCollapsed(this.collapsed);

}

afterAllLoaded = () => {
    let hash = window.location.pathname;

    if (hash === '') {
        hash = 'home';
    }

    const node = this.navTreelistCmp.getStore().findNode('hash', hash);
    this.navTreelistCmp.setSelection(node);
}

readyNavTreelist = (event) => {
    this.navTreelistCmp = event.detail.cmp;
    this.navTreelistCmp.setStore(this.treeStore);
    this.afterAllLoaded();
}

readyToggleButton = (event) => {
    const navButton = event.detail.cmp;

    if (Ext.os.is.Phone) {
        navButton.setHidden(false);
    } else {
        navButton.setHidden(true);
    }

    navButton.on('tap', this.toggleTree);
}

navTreelistSelectionChange = (event) => {
    const record = event.detail.info.node.data.text.toLowerCase().split(' ')[0];
    this.router.navigateByUrl(`/${record}`);

    if(Ext.os.is.Phone) {
        this.collapsed = !this.collapsed;
        this.navTreePanelCmp.setCollapsed(this.collapsed);
    }
}

containsMatches = (node) => {
    const found = node.data.name.match(this.filterRegex) || node.childNodes.some(child => this.containsMatches(child));
    if (found) {
        node.expand();
    }

    node.data.text = node.data.name.replace(this.filterRegex, '<span style="color:#2196F3;font-weight:bold">$1</span>');
    return found;
}

toggleTree = () => {
    if (this.collapsed) {
        this.collapsed = false;
    } else {
        this.collapsed = true;
    }
    this.navTreePanelCmp.setCollapsed(this.collapsed);
  }
}



<ext-container bodyPadding="0" viewport="true">
  <ext-titlebar docked="top">
    <ext-button
        align="left"
        iconCls="x-fa fa-bars"
        (ready)="readyToggleButton($event)"
      >
      </ext-button>
    <span style="height:18px;" href="#" class="app-title">Sencha ExtWebComponents 7.0 Boilerplate App in Angular</span>
  </ext-titlebar>
  <ext-panel
    docked="left"
    border="true"
    shadow="true"
    scrollable="y"
    resizable='{"edges": "east", "dynamic": "true"}'
    header="false"
    collapsible='{"direction": "left"}'
    width="200px"
    (ready)="readyNavTreePanel($event)"
  >
    <ext-treelist
      ui="nav"
      expanderFirst="false"
      expanderOnly="false"
      (ready)="readyNavTreelist($event)"
      (itemclick)="navTreelistSelectionChange($event)">
    </ext-treelist>
  </ext-panel>
  <ext-container width="100%">
    <router-outlet></router-outlet>
  </ext-container>
</ext-container>
